In [ ]:
# !pip3 install sklearn
# !pip3 install pandas
# !pip3 install openpyxl

##Import packages

In [ ]:
from sklearn import preprocessing
import numpy as np
import pandas as pd
import datetime

##Import document as data frame

In [ ]:
df = pd.read_excel('./Fluxo_Escolar_por_Escola.xlsx')

##Drop unused columns

In [ ]:
drop_columns = ['NM_DIRETORIA','CD_REDE_ENSINO',	'CD_ESCOLA', 'APR_1', 'REP_1', 'ABA_1', 'APR_2', 'REP_2', 'ABA_2']
df_cleaned = df.drop(drop_columns, axis='columns')

##Renaming columns

In [ ]:
columns_renamed = {
    'Ano':'ano', 
    'NM_MUNICIPIO':'municipio', 
    'NM_COMPLETO_ESCOLA':'escola', 
    'APR_3':'aprovado', 
    'REP_3':'reprovado', 
    'ABA_3':'abandono'
}
df_cleaned = df_cleaned.rename(columns=columns_renamed)

##Drop rows that contains NaN from data frame (cleaned)

In [ ]:
df_cleaned = df_cleaned.dropna()

In [ ]:
#df_cleaned.head(20)

Exportando o resultado de hoje 07-11 23:31

In [ ]:
df_cleaned.to_excel('fluxo_escolar_parcialmente_tratado.xlsx', encoding="utf-8")

# Cleaning and normalizing data

##Install packages if necessary

In [ ]:
# !pip3 install yellowbrick

##Import packages

In [1]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.metrics import accuracy_score, confusion_matrix
from yellowbrick.classifier import ConfusionMatrix
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import pandas as pd
import seaborn as sns
import datetime
import pickle

##Import document as data frame

In [2]:
df_cleaned = pd.read_excel('./data/Fluxo_Escolar_por_Escola_2021.xlsx',engine='openpyxl')
print(df_cleaned.shape)
df_cleaned.head()

(5194, 16)


ANO_LETIVO NM_DIRETORIA NM_MUNICIPIO  CD_REDE_ENSINO  CD_ESCOLA  \
0        2021       PIRAJU       PIRAJU               1      34320   
1        2021       PIRAJU       PIRAJU               1      34344   
2        2021       PIRAJU       PIRAJU               1      34356   
3        2021       PIRAJU       PIRAJU               1      34459   
4        2021    AMERICANA    AMERICANA               1      17152   

                       NM_COMPLETO_ESCOLA  CD_TP_IDENTIFICADOR  APR_1  REP_1  \
0  JOAQUIM GUILHERME MOREIRA PORTO DOUTOR                    8    0.0    0.0   
1              QUINZINHO CAMARGO PREFEITO                    8    0.0    0.0   
2                    NHONHO BRAGA CORONEL                    8    0.0    0.0   
3                          ATALIBA LEONEL                    8    0.0    0.0   
4             MAURA ARRUDA GUIDOLIN PROFA                    8  100.0    0.0   

   ABA_1   APR_2  REP_2  ABA_2  APR_3  REP_3  ABA_3  
0    0.0  100.00   0.00    0.0  100.0    0.0    0.0  
1    0.0   99.56   0.44    0.0   94.0    2.0    4.0  
2    0.0  100.00   0.00    0.0  100.0    0.0    0.0  
3    0.0  100.00   0.00    0.0  100.0    0.0    0.0  
4    0.0    0.00   0.00    0.0    0.0    0.0    0.0

##Removing fields with "-" value, time value and NaN value

In [3]:
df_cleaned = df_cleaned[df_cleaned != "-"]
df_cleaned = df_cleaned[df_cleaned != datetime.time(0, 0)]
df_cleaned = df_cleaned.dropna()

print(df_cleaned.shape)
df_cleaned.head()

(5194, 16)


ANO_LETIVO NM_DIRETORIA NM_MUNICIPIO  CD_REDE_ENSINO  CD_ESCOLA  \
0        2021       PIRAJU       PIRAJU               1      34320   
1        2021       PIRAJU       PIRAJU               1      34344   
2        2021       PIRAJU       PIRAJU               1      34356   
3        2021       PIRAJU       PIRAJU               1      34459   
4        2021    AMERICANA    AMERICANA               1      17152   

                       NM_COMPLETO_ESCOLA  CD_TP_IDENTIFICADOR  APR_1  REP_1  \
0  JOAQUIM GUILHERME MOREIRA PORTO DOUTOR                    8    0.0    0.0   
1              QUINZINHO CAMARGO PREFEITO                    8    0.0    0.0   
2                    NHONHO BRAGA CORONEL                    8    0.0    0.0   
3                          ATALIBA LEONEL                    8    0.0    0.0   
4             MAURA ARRUDA GUIDOLIN PROFA                    8  100.0    0.0   

   ABA_1   APR_2  REP_2  ABA_2  APR_3  REP_3  ABA_3  
0    0.0  100.00   0.00    0.0  100.0    0.0    0.0  
1    0.0   99.56   0.44    0.0   94.0    2.0    4.0  
2    0.0  100.00   0.00    0.0  100.0    0.0    0.0  
3    0.0  100.00   0.00    0.0  100.0    0.0    0.0  
4    0.0    0.00   0.00    0.0    0.0    0.0    0.0

##Converting datetime values to correct format

In [4]:
for index, row in df_cleaned.iterrows():
    if(isinstance(row['APR_3'], datetime.datetime)):
        if row['APR_3'].month < 10:
            new_value = str(row['APR_3'].day) + ".0" + str(row['APR_3'].month)
        else:
            new_value = str(row['APR_3'].day) + "." + str(row['APR_3'].month)
        df_cleaned['APR_3'] = df_cleaned['APR_3'].replace([row['APR_3']], new_value)

    if(isinstance(row['REP_3'], datetime.datetime)):
        if row['REP_3'].month < 10:
            new_value = str(row['REP_3'].day) + ".0" + str(row['REP_3'].month)
        else:
            new_value = str(row['REP_3'].day) + "." + str(row['REP_3'].month)
        df_cleaned['REP_3'] = df_cleaned['REP_3'].replace([row['REP_3']], new_value)

    if(isinstance(row['ABA_3'], datetime.datetime)):
        if row['ABA_3'].month < 10:
            new_value = str(row['ABA_3'].day) + ".0" + str(row['ABA_3'].month)
        else:
            new_value = str(row['ABA_3'].day) + "." + str(row['ABA_3'].month)
        df_cleaned['ABA_3'] = df_cleaned['ABA_3'].replace([row['ABA_3']], new_value)

print(df_cleaned.shape)
df_cleaned.head()


(5194, 16)


ANO_LETIVO NM_DIRETORIA NM_MUNICIPIO  CD_REDE_ENSINO  CD_ESCOLA  \
0        2021       PIRAJU       PIRAJU               1      34320   
1        2021       PIRAJU       PIRAJU               1      34344   
2        2021       PIRAJU       PIRAJU               1      34356   
3        2021       PIRAJU       PIRAJU               1      34459   
4        2021    AMERICANA    AMERICANA               1      17152   

                       NM_COMPLETO_ESCOLA  CD_TP_IDENTIFICADOR  APR_1  REP_1  \
0  JOAQUIM GUILHERME MOREIRA PORTO DOUTOR                    8    0.0    0.0   
1              QUINZINHO CAMARGO PREFEITO                    8    0.0    0.0   
2                    NHONHO BRAGA CORONEL                    8    0.0    0.0   
3                          ATALIBA LEONEL                    8    0.0    0.0   
4             MAURA ARRUDA GUIDOLIN PROFA                    8  100.0    0.0   

   ABA_1   APR_2  REP_2  ABA_2  APR_3  REP_3  ABA_3  
0    0.0  100.00   0.00    0.0  100.0    0.0    0.0  
1    0.0   99.56   0.44    0.0   94.0    2.0    4.0  
2    0.0  100.00   0.00    0.0  100.0    0.0    0.0  
3    0.0  100.00   0.00    0.0  100.0    0.0    0.0  
4    0.0    0.00   0.00    0.0    0.0    0.0    0.0

##Removing lines with negative number

In [5]:
df_cleaned['ABA_3'] = df_cleaned['ABA_3'].astype(str)
df_cleaned = df_cleaned[df_cleaned["ABA_3"].str.contains("-") == False]

print(df_cleaned.shape)
df_cleaned.head()

(5188, 16)


ANO_LETIVO NM_DIRETORIA NM_MUNICIPIO  CD_REDE_ENSINO  CD_ESCOLA  \
0        2021       PIRAJU       PIRAJU               1      34320   
1        2021       PIRAJU       PIRAJU               1      34344   
2        2021       PIRAJU       PIRAJU               1      34356   
3        2021       PIRAJU       PIRAJU               1      34459   
4        2021    AMERICANA    AMERICANA               1      17152   

                       NM_COMPLETO_ESCOLA  CD_TP_IDENTIFICADOR  APR_1  REP_1  \
0  JOAQUIM GUILHERME MOREIRA PORTO DOUTOR                    8    0.0    0.0   
1              QUINZINHO CAMARGO PREFEITO                    8    0.0    0.0   
2                    NHONHO BRAGA CORONEL                    8    0.0    0.0   
3                          ATALIBA LEONEL                    8    0.0    0.0   
4             MAURA ARRUDA GUIDOLIN PROFA                    8  100.0    0.0   

   ABA_1   APR_2  REP_2  ABA_2  APR_3  REP_3 ABA_3  
0    0.0  100.00   0.00    0.0  100.0    0.0   0.0  
1    0.0   99.56   0.44    0.0   94.0    2.0   4.0  
2    0.0  100.00   0.00    0.0  100.0    0.0   0.0  
3    0.0  100.00   0.00    0.0  100.0    0.0   0.0  
4    0.0    0.00   0.00    0.0    0.0    0.0   0.0

##Convert columns to float

In [8]:
# df_cleaned['APR_3'] = df_cleaned['APR_3'].astype(float)
# df_cleaned['REP_3'] = df_cleaned['REP_3'].astype(float)
# df_cleaned['ABA_3'] = df_cleaned['ABA_3'].astype(float)

df_cleaned['APR_3'] = df_cleaned['APR_3'].astype(int)
df_cleaned['REP_3'] = df_cleaned['REP_3'].astype(int)
df_cleaned['ABA_3'] = df_cleaned['ABA_3'].astype(int)

##Remove rows that have just 0 values and reset index

In [9]:
indexZero = df_cleaned[(df_cleaned['APR_3'] == 0) & (df_cleaned['REP_3'] == 0) & (df_cleaned['ABA_3'] == 0)].index
df_cleaned.drop(indexZero, inplace=True)

df_cleaned = df_cleaned.reset_index()

print(df_cleaned.shape)
df_cleaned.head()

(3739, 17)


index  ANO_LETIVO NM_DIRETORIA NM_MUNICIPIO  CD_REDE_ENSINO  CD_ESCOLA  \
0      0        2021       PIRAJU       PIRAJU               1      34320   
1      1        2021       PIRAJU       PIRAJU               1      34344   
2      2        2021       PIRAJU       PIRAJU               1      34356   
3      3        2021       PIRAJU       PIRAJU               1      34459   
4      6        2021    AMERICANA    AMERICANA               1      17176   

                       NM_COMPLETO_ESCOLA  CD_TP_IDENTIFICADOR  APR_1  REP_1  \
0  JOAQUIM GUILHERME MOREIRA PORTO DOUTOR                    8   0.00   0.00   
1              QUINZINHO CAMARGO PREFEITO                    8   0.00   0.00   
2                    NHONHO BRAGA CORONEL                    8   0.00   0.00   
3                          ATALIBA LEONEL                    8   0.00   0.00   
4                          MAGI MONSENHOR                    8  94.74   5.26   

   ABA_1   APR_2  REP_2  ABA_2  APR_3  REP_3  ABA_3  
0    0.0  100.00   0.00    0.0    100      0      0  
1    0.0   99.56   0.44    0.0     94      2      4  
2    0.0  100.00   0.00    0.0    100      0      0  
3    0.0  100.00   0.00    0.0    100      0      0  
4    0.0   93.35   6.65    0.0     79     19      0

##Rename fields

In [10]:
df_cleaned = df_cleaned.rename(columns={'Ano':'ano', 'NM_MUNICIPIO':'municipio', 'CD_REDE_ENSINO':'id_rede_ensino', 'CD_ESCOLA':'id_escola', 'NM_COMPLETO_ESCOLA':'escola', 'APR_3':'aprovado', 'REP_3':'reprovado', 'ABA_3':'abandono'})
df_cleaned.head()

index  ANO_LETIVO NM_DIRETORIA  municipio  id_rede_ensino  id_escola  \
0      0        2021       PIRAJU     PIRAJU               1      34320   
1      1        2021       PIRAJU     PIRAJU               1      34344   
2      2        2021       PIRAJU     PIRAJU               1      34356   
3      3        2021       PIRAJU     PIRAJU               1      34459   
4      6        2021    AMERICANA  AMERICANA               1      17176   

                                   escola  CD_TP_IDENTIFICADOR  APR_1  REP_1  \
0  JOAQUIM GUILHERME MOREIRA PORTO DOUTOR                    8   0.00   0.00   
1              QUINZINHO CAMARGO PREFEITO                    8   0.00   0.00   
2                    NHONHO BRAGA CORONEL                    8   0.00   0.00   
3                          ATALIBA LEONEL                    8   0.00   0.00   
4                          MAGI MONSENHOR                    8  94.74   5.26   

   ABA_1   APR_2  REP_2  ABA_2  aprovado  reprovado  abandono  
0    0.0  100.00   0.00    0.0       100          0         0  
1    0.0   99.56   0.44    0.0        94          2         4  
2    0.0  100.00   0.00    0.0       100          0         0  
3    0.0  100.00   0.00    0.0       100          0         0  
4    0.0   93.35   6.65    0.0        79         19         0

##Normalizing data

In [ ]:
# normalized_list = preprocessing.normalize([df_cleaned['aprovado'],df_cleaned['reprovado'],df_cleaned['abandono']])

# df_cleaned['aprovado_normalized'] = normalized_list[0]
# df_cleaned['reprovado_normalized'] = normalized_list[1]
# df_cleaned['abandono_normalized'] = normalized_list[2]

# df_cleaned.head()

##Creating normalized file

In [11]:
df_cleaned.to_excel('./data/FluxoEscolarNormalizado.xlsx', encoding="utf-8")

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/util/_decorators.py:211: FutureWarning: the 'encoding' keyword is deprecated and will be removed in a future version. Please take steps to stop the use of 'encoding'
  return func(*args, **kwargs)


# Start of creating the predictive model

#Check point: Open the file created from the normalization above

In [75]:
df = pd.read_excel('./data/FluxoEscolarNormalizado.xlsx', engine='openpyxl')
# df = df.drop(['Unnamed: 0', 'index', 'aprovado', 'reprovado', 'abandono','escola', 'reprovado_normalized', 'abandono_normalized'], axis='columns')
df = df.drop(['Unnamed: 0', 'index', 'reprovado', 'abandono','escola'], axis='columns')
df = df.drop(['ANO_LETIVO', 'NM_DIRETORIA', 'CD_TP_IDENTIFICADOR', 'APR_1', 'REP_1','ABA_1', 'APR_2', 'REP_2', 'ABA_2'], axis='columns')
df.head()

municipio  id_rede_ensino  id_escola  aprovado
0     PIRAJU               1      34320       100
1     PIRAJU               1      34344        94
2     PIRAJU               1      34356       100
3     PIRAJU               1      34459       100
4  AMERICANA               1      17176        79

#Scraping the data to decrease bias

In [76]:
random_df = df.sample(frac=1).reset_index(drop=True)
random_df.head()

municipio  id_rede_ensino  id_escola  aprovado
0  SAO JOSE DOS CAMPOS               1     917266        94
1          JABOTICABAL               1     922511        98
2            SAO PAULO               1       3724        84
3           PIRACICABA               1      20928       100
4               ITAOCA               1      48203       100

#Split the data frame between training and testing

In [77]:
train, test = train_test_split(random_df, test_size=0.2)

## Handling training data

#Split between predictors and classes

In [78]:
train.columns

Index(['municipio', 'id_rede_ensino', 'id_escola', 'aprovado'], dtype='object')

#Get all the feature examples

In [79]:
x_df_train = train.iloc[:, 0:3].values
x_df_train

array([['SAO SEBASTIAO', 1, 11289],
       ['BARUERI', 1, 40548],
       ['SAO PAULO', 1, 3931],
       ...,
       ['ITAPEVA', 1, 15477],
       ['BARRA BONITA', 1, 26062],
       ['TEODORO SAMPAIO', 1, 32177]], dtype=object)

#Get all labels from the target

In [80]:
y_df_train = train.iloc[:, -1].values
y_df_train

array([100, 100, 100, ..., 100, 100, 100])

#Handling categorical data with one hot encoder

In [81]:
onehotencoder_train = ColumnTransformer(transformers=[('OneHot', OneHotEncoder(), [0])], remainder='passthrough')

In [82]:
x_df_train = onehotencoder_train.fit_transform(x_df_train).toarray()
x_df_train[0]

array([0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e

## Handling test data

#Split between predictors and classes

In [83]:
test.columns

Index(['municipio', 'id_rede_ensino', 'id_escola', 'aprovado'], dtype='object')

#Get all the feature examples

In [84]:
x_df_test = test.iloc[:, 0:3].values
x_df_test

array([['MOGI MIRIM', 1, 389511],
       ['PORTO FELIZ', 1, 15611],
       ['CAIUA', 1, 904211],
       ...,
       ['CARAPICUIBA', 1, 908538],
       ['GUARULHOS', 1, 6440],
       ['LARANJAL PAULISTA', 1, 16559]], dtype=object)

#Get all labels from the target

In [85]:
y_df_test = test.iloc[:, -1].values
y_df_test

array([ 96, 100, 100, 100,  99,  87,  94,  89,  99, 100,  98, 100,  90,
        74, 100, 100, 100, 100,  99,  94,  93,  88, 100,  98, 100, 100,
        94, 100, 100,  96,  99,  97,  97, 100,  98,  98, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100,  92, 100,  81,  99, 100,  99,
       100,  87,  98, 100,  81, 100,  97, 100,  96,  96,  86, 100, 100,
       100, 100, 100,  84, 100, 100,  98, 100,  98,  98, 100,  96,  95,
        98,  99,  96,  99, 100,  93, 100,  97, 100,  95, 100, 100,  99,
        97, 100, 100, 100, 100,  99, 100,  92,  96, 100,  85, 100, 100,
        99, 100, 100, 100, 100, 100, 100,  97,  99, 100, 100,  99,  83,
        98,  99, 100,  98, 100, 100,  91,  83,  98,  98,  96, 100, 100,
        97, 100, 100,  99, 100, 100,  94,  94,  97,  99, 100, 100, 100,
       100, 100, 100, 100,  99, 100, 100,  99,  88,  99,  94,  95, 100,
       100,  96,  97,  98, 100,  96,  99,  98,  98, 100, 100, 100, 100,
       100,  97,  97, 100, 100,  99, 100, 100, 100, 100,  99,  9

#Handling categorical data with one hot encoder

In [86]:
onehotencoder_test = ColumnTransformer(transformers=[('OneHot', OneHotEncoder(), [0])], remainder='passthrough')

In [87]:
x_df_test = onehotencoder_test.fit_transform(x_df_test)
x_df_test[0]

<1x275 sparse matrix of type '<class 'numpy.float64'>'
	with 3 stored elements in Compressed Sparse Row format>

##Save variables

In [88]:
with open('students.pickle', mode='wb') as f:
    pickle.dump([x_df_train, y_df_train, x_df_test, y_df_test], f)

### Naive Bayes Model

In [89]:
from sklearn.naive_bayes import GaussianNB

In [90]:
print(x_df_train)

[[0.0000e+00 0.0000e+00 0.0000e+00 ... 0.0000e+00 1.0000e+00 1.1289e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 ... 0.0000e+00 1.0000e+00 4.0548e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 ... 0.0000e+00 1.0000e+00 3.9310e+03]
 ...
 [0.0000e+00 0.0000e+00 0.0000e+00 ... 0.0000e+00 1.0000e+00 1.5477e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 ... 0.0000e+00 1.0000e+00 2.6062e+04]
 [0.0000e+00 0.0000e+00 0.0000e+00 ... 0.0000e+00 1.0000e+00 3.2177e+04]]


In [95]:
students_naive = GaussianNB()
students_naive.fit(x_df_train, y_df_train)

GaussianNB()

In [96]:
naive_predict = students_naive.predict(x_df_test)
naive_predict

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/utils/validation.py:727: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  warnings.warn(


ValueError: X has 275 features, but GaussianNB is expecting 571 features as input.

In [ ]:
naive_score = accuracy_score(y_df_test, naive_predict)
naive_score